import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Importing the custom fonts
const gambetta = localFont({
  src: "./fonts/Gambetta-Variable.ttf",
  variable: "--font-gambetta", // Define a CSS variable to use in the global stylesheet
  weight: "100 900",
});
const generalSans = localFont({
  src: "./fonts/GeneralSans-Variable.ttf",
  variable: "--font-gs", // Define a CSS variable to use in the global stylesheet
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body
        className={`${gambetta.variable} ${generalSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
